# RDS PostgreSQL for the Hawknetic platform.
#
# The design constraints here are not generic. They come from the incident that
# prompted this migration: a 5 GB Railway volume filled with raw payloads at
# ~166 MB/day, PostgreSQL could not create a WAL segment, and the database
# would not start. See docs/aws-migration/database-recovery.md.
#
# Three things in this module exist specifically so that cannot recur:
#
#   1. max_allocated_storage -- storage autoscaling. RDS grows the volume on
#      its own before it fills. This is the single most important setting in
#      the file and it is why allocated_storage can start small.
#   2. A FreeStorageSpace alarm in the observability module, firing with room
#      to act rather than at the cliff.
#   3. A place for aged raw payloads to go instead of accumulating in
#      PostgreSQL forever. The S3 bucket and the task role's access to it exist;
#      the application change that would write to them does NOT, so today this
#      is a prepared destination rather than a working archive. Items 1 and 2
#      are what currently prevent a repeat.
#
# Credentials are generated by RDS and stored in Secrets Manager. No password
# is ever passed through Terraform configuration, so none can land in state as
# a plaintext input or in a .tfvars file in the repository.

locals {
  # Backup retention is not a preference. A database with no verified backup is
  # what turned a full disk into an incident with no rollback.
  backup_retention = var.environment == "prod" ? 14 : 7

  # Derive the parameter group family from engine_version rather than taking it
  # as a second input. When the two were separate variables, bumping
  # engine_version to 19.x without also changing engine_major_version produced
  # a postgres18 family against a 19 engine, and RDS rejected it at apply.
  engine_major = split(".", var.engine_version)[0]
}

resource "aws_db_subnet_group" "this" {
  name        = "${var.name_prefix}-db"
  description = "Isolated subnets for ${var.name_prefix} PostgreSQL"
  subnet_ids  = var.subnet_ids

  tags = merge(var.tags, { Name = "${var.name_prefix}-db" })
}

resource "aws_security_group" "this" {
  name        = "${var.name_prefix}-db"
  description = "PostgreSQL access for ${var.name_prefix}"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, { Name = "${var.name_prefix}-db" })
}

# Ingress is by security group reference only. There is deliberately no CIDR
# rule and no variable that would accept one: 5432 open to 0.0.0.0/0 is the
# failure this module is built to make unrepresentable.
resource "aws_vpc_security_group_ingress_rule" "from_tasks" {
  for_each = toset(var.allowed_security_group_ids)

  security_group_id            = aws_security_group.this.id
  description                  = "PostgreSQL from an authorised workload security group"
  referenced_security_group_id = each.value
  from_port                    = 5432
  to_port                      = 5432
  ip_protocol                  = "tcp"
}

resource "aws_kms_key" "this" {
  description             = "Encryption at rest for ${var.name_prefix} PostgreSQL"
  deletion_window_in_days = 30
  enable_key_rotation     = true

  tags = merge(var.tags, { Name = "${var.name_prefix}-rds" })
}

resource "aws_kms_alias" "this" {
  name          = "alias/${var.name_prefix}-rds"
  target_key_id = aws_kms_key.this.key_id
}

resource "aws_db_parameter_group" "this" {
  name        = "${var.name_prefix}-pg${local.engine_major}"
  family      = "postgres${local.engine_major}"
  description = "Parameter group for ${var.name_prefix}"

  # Log statements slower than a second. Cheap, and the thing you wish you had
  # turned on before the incident rather than after it.
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }

  parameter {
    name  = "log_connections"
    value = "1"
  }

  parameter {
    name  = "log_disconnections"
    value = "1"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = var.tags
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-pg"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  # Storage autoscaling: start at allocated_storage and let RDS grow to
  # max_allocated_storage as needed. gp3 rather than gp2 -- baseline IOPS are
  # not tied to volume size, so a small volume is not also a slow one.
  storage_type          = "gp3"
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage

  storage_encrypted = true
  kms_key_id        = aws_kms_key.this.arn

  db_name  = var.database_name
  username = var.master_username

  # RDS generates the password and writes it to a Secrets Manager secret it
  # manages. Terraform never sees it.
  #
  # This also means RDS rotates it: "RDS manages the settings for the secret
  # and rotates the secret every seven days by default." ECS injects secrets
  # only at task start, so resident tasks keep a password that stops working
  # about a week after deployment. See the KNOWN GAP section in
  # docker-entrypoint.sh for the symptom and the three ways to close it; it is
  # an open decision, not an oversight, and it must be settled before
  # production traffic moves.
  #
  # The alternative -- a Terraform-generated random_password -- is worse on two
  # counts and was rejected: it puts the password in state as plaintext, and it
  # replaces weekly rotation with none at all.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = aws_kms_key.this.key_id

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]
  parameter_group_name   = aws_db_parameter_group.this.name

  # Not negotiable, and not exposed as a variable.
  publicly_accessible = false

  multi_az                 = var.multi_az
  backup_retention_period  = local.backup_retention
  backup_window            = "07:00-08:00"
  maintenance_window       = "Mon:08:30-Mon:09:30"
  copy_tags_to_snapshot    = true
  delete_automated_backups = false

  # Production must not be destroyable by a plan nobody read carefully.
  deletion_protection       = var.environment == "prod"
  skip_final_snapshot       = var.environment != "prod"
  final_snapshot_identifier = var.environment == "prod" ? "${var.name_prefix}-pg-final-${var.final_snapshot_suffix}" : null

  performance_insights_enabled          = true
  performance_insights_kms_key_id       = aws_kms_key.this.arn
  performance_insights_retention_period = 7

  monitoring_interval = 60
  monitoring_role_arn = aws_iam_role.monitoring.arn

  # Referencing the role only orders this after the role itself. Enhanced
  # Monitoring needs the managed policy attached too, and without this the
  # instance can be created first and monitoring setup fails on a race.
  depends_on = [aws_iam_role_policy_attachment.monitoring]

  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  auto_minor_version_upgrade = true
  apply_immediately          = var.environment != "prod"

  tags = merge(var.tags, { Name = "${var.name_prefix}-pg" })

  lifecycle {
    # An engine_version drift from an auto minor upgrade should not show up as
    # a plan wanting to downgrade the database.
    ignore_changes = [engine_version]
  }
}

resource "aws_iam_role" "monitoring" {
  name = "${var.name_prefix}-rds-monitoring"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "monitoring.rds.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = var.tags
}

resource "aws_iam_role_policy_attachment" "monitoring" {
  role       = aws_iam_role.monitoring.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}
