variable "name_prefix" {
  description = "Prefix applied to every resource name, e.g. hawknetic-prod."
  type        = string
}

variable "environment" {
  description = "Environment name. 'prod' turns on deletion protection and a final snapshot, and lengthens backup retention."
  type        = string

  validation {
    condition     = contains(["dev", "prod"], var.environment)
    error_message = "environment must be dev or prod."
  }
}

variable "vpc_id" {
  description = "VPC to create the database security group in."
  type        = string
}

variable "subnet_ids" {
  description = "Isolated subnet ids for the DB subnet group. These must have no internet route."
  type        = list(string)
}

variable "allowed_security_group_ids" {
  description = "Security groups permitted to reach 5432. Reference only -- there is intentionally no CIDR-based ingress variable."
  type        = list(string)
  default     = []
}

variable "engine_version" {
  description = "PostgreSQL engine version. The parameter group family is derived from its major component, so the two cannot drift apart. Verify the minor version is offered in the target region before applying: aws rds describe-db-engine-versions --engine postgres --region us-east-2"
  type        = string
  default     = "18.1"
}

variable "instance_class" {
  description = "Instance class. db.t4g.micro is Graviton and the cheapest sensible production-shaped option for this workload."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Initial storage in GB. Starts small because max_allocated_storage lets RDS grow it automatically."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Storage autoscaling ceiling in GB. This is the setting that prevents a repeat of the Railway full-volume incident; do not set it equal to allocated_storage, which disables autoscaling."
  type        = number
  default     = 100

  validation {
    condition     = var.max_allocated_storage > var.allocated_storage
    error_message = "max_allocated_storage must exceed allocated_storage, otherwise storage autoscaling is disabled and a full volume becomes an outage."
  }
}

variable "multi_az" {
  description = "Multi-AZ deployment. Roughly doubles instance cost; buys automatic failover."
  type        = bool
  default     = false
}

variable "database_name" {
  description = "Initial database name."
  type        = string
  default     = "hawknetic"
}

variable "master_username" {
  description = "Master username. The password is generated by RDS and held in Secrets Manager; it is never a Terraform input."
  type        = string
  default     = "hawknetic"
}

variable "final_snapshot_suffix" {
  description = "Suffix for the production final snapshot identifier. Change it to avoid colliding with an existing snapshot name."
  type        = string
  default     = "v1"
}

variable "tags" {
  description = "Tags applied to every resource."
  type        = map(string)
  default     = {}
}
